from typing import TYPE_CHECKING

from sqlalchemy import Column
from sqlmodel import Field, Relationship, SQLModel, Enum as SQLModelEnum

from src.exercises.enums import DifficultyEnum
from src.utils import enum_values

if TYPE_CHECKING:
    from src.logs.models import ExerciseLogs
    from src.stats.models import UserStats


class ExerciseType(SQLModel, table=True):
    __tablename__ = "exercise_types"
    id: int | None = Field(default=None, primary_key=True)
    type: str = Field(nullable=False, unique=True)

    exercises: list["Exercise"] = Relationship(back_populates="exercise_type",
                                               sa_relationship_kwargs={"lazy": "selectin"}, )


class Exercise(SQLModel, table=True):
    __tablename__ = "exercises"
    id: int | None = Field(default=None, primary_key=True)
    exercise_name: str = Field(nullable=False, unique=True)
    slug: str = Field(nullable=False,
                      description="It is a url friendly name of this exercise generated by processing worker(ideally)")
    difficulty: DifficultyEnum = Field(
        description="Difficulty of the exercise, available types: Easy, Medium, Hard",
        sa_column=Column(
            nullable=False,
            type_=SQLModelEnum(DifficultyEnum, values_callable=enum_values, name="difficulty"),
        ))
    exercise_duration: int = Field(nullable=False, default=0, description="exercise duration in seconds")
    rating: int = Field(nullable=False, default=0, description="exercise rating in scale 1 - 100")
    type: int = Field(nullable=False, foreign_key="exercise_types.id",
                      description="foreign key to exercise type, exercise type consists of: id: int, type: str")

    stats: list["UserStats"] = Relationship(back_populates="exercise", sa_relationship_kwargs={"lazy": "selectin"})
    exercise_type: ExerciseType = Relationship(back_populates="exercises", sa_relationship_kwargs={"lazy": "selectin"})
    exercise_logs: list["ExerciseLogs"] = Relationship(back_populates="exercise",
                                                       sa_relationship_kwargs={"lazy": "selectin"})


class ProcessExercise(SQLModel, table=True):
    __tablename__ = "task_queue"
    id: int | None = Field(default=None, primary_key=True)
    exercise_name: str = Field(nullable=False,
                               description="exercise name to process it will be needed to generate exercise row")
    exercise_path: str = Field(nullable=False,
                               description="exercise path to process, it will show us path to s3 bucket from which we will download it and locally download it to process")
    exercise_id: int = Field(default=None,
                             description="exercise row id, it will be needed for storing processed exercise in s3 bucket, the path to every exercise will look like that: exercises/{id}/...")
    # when i have time and patience i can think about enums etc.
    status: str = Field(nullable=False, default=None,
                        description="Exercise status(for now it is a string but later type will be an enum, shows us exercise process status, it can be Waiting, Processing, Successfully processed")


# i don't know how to name it, so i will name it that way
class ExerciseAvailabilityLog(SQLModel, table=True):
    __tablename__ = "active_exercises"
    log_id: int = Field(default=None, primary_key=True,
                        description="It's id of our attempt, it is used for additional security and faster extracting secret token")
    secret_exercise_token: str = Field(nullable=False,
                                       description="It's secret token for this exercise attempt, it's one-time use, and if it's not present in database means somebody already used it, it's used to complicate faking results and to ensure user can end exercise when he started it without logging again")
