[project]
name = "server"
version = "0.1.0"
description = "Initial uv configuration"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "boto3>=1.43.58",
    "boto3-stubs[s3]~=1.43.58",
    "fastapi[standard]>=0.139.2",
    "numpy<=2.0.0",
    "psycopg2>=2.9.12",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "sqlmodel>=0.0.39",
    "botocore>=1.43.58",
]
